ARG NODE_VERSION=16.15
ARG NGINX_VERSION=1.22.1

FROM node:${NODE_VERSION} as builder

WORKDIR /usr/src/app

COPY ./package.json ./package-lock.json ./

RUN npm install

COPY .. .

RUN npm run build --prod

FROM nginx:${NGINX_VERSION}
COPY docker/nginx/http.conf /etc/nginx/conf.d/http.conf
RUN rm /etc/nginx/conf.d/default.conf
COPY --from=builder /usr/src/app/dist/ng-pokemon-app/ /usr/share/nginx/html

